[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Runic = "62bfec6d-59d7-401d-8490-b29ee721c001"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TNRKit = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
